apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo-statefulset
spec:
  serviceName: mongo-service
  replicas: 1
  template:
    metadata:
      labels:
        app: mongo-app
    spec:
      containers:
        - name: mongo-container
          image: mongo
          envFrom:
            - secretRef:
                name: api-prod-env
          ports:
            - containerPort: 27017
              name: mongo-cli
          volumeMounts:
            - mountPath: "/data/db"
              name: mongo-pvc

  selector:
    matchLabels:
      app: mongo-app
  volumeClaimTemplates:
    - metadata:
        name: mongo-pvc
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 100Mi