apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: rabbitmq-statefulset
spec:
  serviceName: rabbitmq-service
  replicas: 1
  template:
    metadata:
      labels:
        app: rabbitmq-app
    spec:
      containers:
        - name: rabbitmq-container
          image: rabbitmq:3-management
          envFrom:
            - configMapRef:
              name: api-configs
            - secretRef:
              name: api-prod-env
          env:
            - name: RABBITMQ_DEFAULT_USER
              value: user
            - name: RABBITMQ_DEFAULT_PASS
              value: password
          ports:
            - containerPort: 15672
              name: rabbit-ui
            - containerPort: 5672
              name: rabbitmq
          volumeMounts:
            - mountPath: "/var/log/rabbitmq"
              name: rabbitmq-log-pvc
            - mountPath: "/var/lib/rabbitmq"
              name: rabbitmq-lib-pvc

  selector:
    matchLabels:
      app: rabbitmq-app
  volumeClaimTemplates:
    - metadata:
        name: rabbitmq-log-pvc
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 100Mi
    - metadata:
        name: rabbitmq-lib-pvc
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 100Mi