apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: admin-app
    spec:
      containers:
        - name: admin-container
          image: {{ .Values.imagesStorage }}k8s-admin:latest
          envFrom:
{{ toYaml .Values.envFrom | indent 12 }}
          env:
          - name: DEBUG
            value: "True"         
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
        
        - name: admin-nginx-container
          image: {{ .Values.imagesStorage }}k8s-admin-nginx:latest
          envFrom:
{{ toYaml .Values.envFrom | indent 12 }}  
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          volumeMounts:
            - name: admin-nginx-conf
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
              readOnly: true
            - name: admin-nginx-conf
              mountPath: /etc/nginx/conf.d/configs/admin.conf
              subPath: admin.conf
              readOnly: true
      volumes:
      - name: admin-nginx-conf
        configMap:
          name: admin-nginx-conf
          items:
            - key: nginx.conf
              path: nginx.conf
            - key: admin.conf
              path: admin.conf
  selector:
    matchLabels:
      app: admin-app